FROM node:25

WORKDIR /frontend

COPY package*.json ./
RUN npm ci

EXPOSE 4000
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4000", "--allowed-hosts", "localhost", "--poll", "2000"]
