FROM node:25

WORKDIR /frontend

COPY package*.json ./
RUN npm ci

EXPOSE 4200
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200", "--allowed-hosts", "frontend", "--poll", "2000"]
