spring:
  application:
    name: backend
  jackson:
    property-naming-strategy: SNAKE_CASE
  web:
    error:
      whitelabel:
        enabled: false
  servlet:
    multipart:
      max-file-size: 5MB

mediastorage:
  endpoint: http://mediastorage:9000
  user: ${MINIO_ROOT_USER}
  password: ${MINIO_ROOT_PASSWORD}