name: Formatting Code

on: [pull_request]

env:
  JAVA_VERSION: 25

jobs:
  spotless:
    name: Spotless
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend
        uses: actions/checkout@v6
        with:
          sparse-checkout: 'backend'
          sparse-checkout-cone-mode: 'true'

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
          cache-dependency-path: 'backend/pom.xml'

      - name: Run Formatting Check
        working-directory: backend
        run: ./mvnw spotless:check
